# Header
menu:
  #主页: /archives
  关于我: /resume
  #主页: /
  前端开发: /categories/front
  工作日志: /categories/work
  低吟浅谈: /categories/life

subnav:
  github: "https://github.com/Kiritor"
  weibo: "http://weibo.com/3206206100/profile?topnav=1&wvr=6"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/kiritor"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: More
archive_yearly: true #按年存档
fancybox: true
mathjax: false

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.ico

#你的头像url
avatar: "http://kiritor.github.io/img/lcore.jpg"

#是否开启分享
socialShare: true

#是否开启云标签
tagcloud: true

#是否开启评论
valine: true
#是否开启多说最近评论:悬浮于首页(目前弃用多说)
#recentComment: false

#是否开启捐赠
donate: true

#是否开启站内搜索
search: true

#是否开启目录
toc: true

#是否开启最近通知
recent: true
recentContent: 最近打算回归学习,记录一点东西,慢慢找回写博客的习惯...

#是否开启微简历
resume: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
  #奥巴马的博客: http://localhost:4000/
  #卡卡的美丽传说: http://localhost:4000/
   #本泽马的博客: http://localhost:4000/
  #吉格斯的博客: http://localhost:4000/
  #习大大大不同: http://localhost:4000/
  #托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 乐于分享,喜欢环境音乐,爱看动漫,偶尔写写技术博客的小程一枚...
